[build]
  command = "npm run ntlbuild"
  functions = "src/functions"
  publish = "public"

[[redirects]]
  from = "/api/signup-service"
  to = "/.netlify/functions/signup-service"
  status = 200

[[redirects]]
  from = "/api/fellows-survey"
  to = "/.netlify/functions/fellows-survey"
  status = 200

